export const CREAR_CITA = 'CREAR_CITA';
export const ACTUALIZAR_CITA = 'ACTUALIZAR_CITA';
export const ELIMINAR_CITA = 'ELIMINAR_CITA';
export const BUSCAR_CITAS = 'BUSCAR_CITAS';
export const RECUPERAR_CITA = 'RECUPERAR_CITA';
